sudo: required

services:
  - docker

before_install:
  - docker build -t mprzybolewski/frontend -f frontend/Dockerfile.dev frontend/

script:
  - docker run -e CI=true mprzybolewski/frontend yarn test